config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }
  
  resources :products do
    resources :comments
  end
  resources :users

  mount ActionCable.server => '/cable'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
  get 'static_pages/landing_page'

  get 'products/index'

  get 'static_pages/payment_thank_you'

  post 'static_pages/thank_you'

  post 'payments/create'
  
  root 'static_pages#index'


  resources :orders, only: [:index, :show, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wedekind's Sports World</title>
    

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>

  
  </head>

  <body>

  	<% if notice %>
    	<p id="notice" class="alert alert-info"><%= notice %></p>
		<% end %>
		<% if alert %>
    	<p id="alert" class="alert alert-danger"><%= alert %></p>
		<% end %>
  	
		<nav class="navbar navbar-default navbar-fixed-top">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="#">WSW</a>
		    </div>


		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav nav-item">
		        <li class="active"><%= link_to "Home", static_pages_landing_page_path %><span class="sr-only">(current)</span></li>
		        <li><%= link_to "About", static_pages_about_path %></li>
		        <li><%= link_to "Contact", static_pages_contact_path %></li>
		        <li><%= link_to('Products', products_path) %></li>
		      </ul>
		      <ul class="nav pull-right">
					  <li>
					  <% if user_signed_in? %>
					    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
					  <% else %>
					    <%= link_to('Login', new_user_session_path) %>
					  <% end %>
					  </li>
					</ul>
		      <form class="navbar-form navbar-right">
		        <div class="form-group">
		          <!-- <input type="text" class="form-control" placeholder="Search"> -->
		          <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
  							<%= form.text_field :q, id: 'q', value: params[:q], class: 'form-control'  %>
  							<span class="form-group-btn">
  								<%= form.submit 'Search', class: 'btn btn-default' %>
  							</span>
							<% end %>
		        </div>
		        <!-- <button type="submit" class="btn btn-default">Submit</button> -->
		      </form>
		      <ul class="nav navbar-nav navbar-right">
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->

		</nav>


    <%= yield %>

    <footer>
    	<div>
    		<span></span>
    	</div>
    </footer>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">&copy; 2017 Chase Wedekind </span>
      </div>
    </footer>

  </body>

</html>